//独立COOKIE文件     ck在``里面填写，多账号换行

let qmydtokenVal = `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgyMjYxMCwiZXhwIjoyMDUzNjQyMjYxMCwibmJmIjoxNjE0ODIyNjEwLCJqdGkiOiJlRHEzdzdZMmlETGw4RUhiIiwic3ViIjoxMTYxMTIsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.qJp1Jv0qfW8p_5O2Zk_UmWjMcj-Nqi8xz5TUxax9PiU
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgyMjk5NywiZXhwIjoyMDUzNjQyMjk5NywibmJmIjoxNjE0ODIyOTk3LCJqdGkiOiJaOE1nWDFKeUFpcFBRWlNlIiwic3ViIjoxMTYxMjYsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.GGwCSfMBqsbgsI91xZGuFSuGgxAp9cmy_8hg8OZtADQ
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgyMzIzMywiZXhwIjoyMDUzNjQyMzIzMywibmJmIjoxNjE0ODIzMjMzLCJqdGkiOiJ3UjNyVWkwMTFRZ2dKbTlaIiwic3ViIjoxMTYxMzMsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.1HALnEAcNFSIWZv1gxQf6SCQcSXllw2B3RLmbZJu0js`








let qmydcookie = {

    qmydtokenVal: qmydtokenVal,

}

module.exports = qmydcookie
